```{r}
library(TraMineR)
library(markovchain)
library(DiscreteWeibull)
library(readr)
```

```{r}
data <- per_week[1:22,4:24]
data
```
```{r}
seq <- seqdef(data,states = c("Low","Medium","High"))
#png(filename = 'discret.jpg',width = 6000,height = 4000,res=400)
par(mfrow=c(1,2))
cpal(seq) <- c("#9acc99","#9a99ff","#ff9899")
seqIplot(seq, withlegend = F, title = "")
seqlegend(seq, fontsize = 1.3)
```
```{r}
df = as.matrix(sapply(data, as.numeric))  
df = matrix(df,nrow = 22,byrow = FALSE)

```

```{r}
fonction <- function(x,state0,state1){
  row <- dim(x)[1]
  col <- dim(x)[2]
  sejour <- c()
  for (l in seq(1:row)) {
    j=0
    for (i in seq(1:col)) {
      if (x[l,i] ==state0){j=j+1} 
      else if (x[l,i]!=state0){if(j!=0){sejour <- append(sejour,j) 
      j=0}}
      else{j=0}
    }
  }
return(sejour)
}
sejour <- fonction(df,3,2)
lamda <- length(sejour)/sum(sejour)
gama <- ((sum(sejour))/(length(sejour)))
table(sejour)
lamda
gama
etd = estdweibull(sejour,method = "ML")
etd
```

```{r}
T1=table(sejour)
k=1:25
geom = lamda*(1-lamda)^(k)
pois = (gama^k)*exp(-gama)/factorial(k)
beta <- 2
weibull = lamda^((k-1)^beta)-(lamda^(k^beta))
#png(filename = 'high.jpg',width = 4000,height = 2000,res=400)
plot(T1/sum(T1),lwd=10,xlab = "Sojourn time",ylab = "",col="black")
lines(geom,lwd=5,col='red',type = "h")
legend(x="topright",legend=c("Empirical estimator","EMV(Geometric law)"),lwd = c(3, 3),col = c("black","red"))
ks.test(T1, "pgeom", lamda)
ks.test(T1, "ppois", gama)
ks.test(T1, "pdweibull",q=etd[1],beta=etd[2])
#ks.test(T1, "dnbinom", size=n,prob=p)
```
```{r}
Q1 <- matrix(c(0,.8,.2,.857,0,.143,.5,.5,0),byrow = TRUE,ncol = 3)
Q2 <- matrix(c(0,.833,.167,.533,0,.467,0.333,0.667,0),byrow = TRUE,ncol = 3)
Q <- matrix(c(0,.375,.625,.350,0,.650,.211,0.789,0),byrow = TRUE,ncol = 3)
QG <- matrix(c(0,0.66,0.34,0.5,0,0.5,0.25,0.75,0),byrow = TRUE,ncol = 3)
#Bayesienne
f <- function(k){
  matrix(c(0,dpois(k,5.01),ddweibull(k,q=0.63,beta=0.64,zero=TRUE),dgeom(k,0.654),0,dgeom(k,0.444),dgeom(k,0.62),dgeom(k,0.33),0),nrow = 3,byrow = TRUE)
}
#Vraisemblance
#f <- function(k){
#  matrix(c(0,dpois(k,5.37),ddweibull(k,q=0.63,beta=0.64,zero=TRUE),dgeom(k,0.75),0,dgeom(k,0.41),dgeom(k,1),dgeom(k,0.24),0),nrow = 3,byrow = TRUE)
#}
noyau <- function(k){
  if (k==0){
    return (matrix(c(1,0,0,0,1,0,0,0,1),ncol=3,byrow = T))
  }
  else{
  return(Q*f(k))
  }
}
f(0)
Q
```


```{r}
H1 <- function(k){
     h1 <- 0
     for(l in 1:k){
         h1 <- h1+sum(Q[1,]*f(l)[1,])
         }
return(h1)}

H2 <- function(k){
     h2 <- 0
     for(l in 1:k){
         h2 <- h2+sum(Q[2,]*f(l)[2,])
         }
return(h2)}

H3 <- function(k){
     h3 <- 0
     for(l in 1:k){
         h3 <- h3+sum(Q[3,]*f(l)[3,])
         }
return(h3)}



IH <- function(k){
  diag(c(1-H1(k),1-H2(k),1-H3(k)))
}
```


```{r}
m1 <- function(k){
     m1=0
     for(l in 1:k){
         m1=m1+(1-H1(k))}
return(m1)
}

m2 <- function(k){
     m2=0
     for(l in 1:k){
         m2=m2+(1-H2(k))}
return(m2)
}
m3 <- function(k){
     m3=0
     for(l in 1:k){
         m3=m3+(1-H3(k))}
return(m3)
}

m1(40)
m2(40)
m3(40)
nu = matrix(c(m1(100),m2(100),m3(100)),nrow=1)
```
```{r}
statesNames <- c("Low", "Medium", "High")
markovB <- new("markovchain", states = statesNames, transitionMatrix =
                matrix(c(0,.375,.625,.350,0,.650,.211,0.789,0), nrow = 3,
                byrow = TRUE, dimnames=list(statesNames,statesNames)),
               name = "A markovchain Object" 
)     
pi = steadyStates(markovB)
round(nu * pi / sum(nu * pi),digits = 3)

```

